version: '3'
networks:
  kafka-net:
    driver: bridge
  hdfs-net:
    driver: bridge

services:
  kafk-1:
    image: apache/kafka:3.9.0
    container_name: kafk-1
    hostname: kafk-1
    networks:
      - hdfs-net
      - kafka-net
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafk-1:9093,2@kafk-2:9093,3@kafk-3:9093
      - KAFKA_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,PLAINTEXT://:9094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafk-1:9092,CONTROLLER://kafk-1:9093,PLAINTEXT://kafk-1:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_LOG_DIRS=/tmp/kraft-combined_logs
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    ports:
      - 29092:9094

  kafk-2:
    image: apache/kafka:3.9.0
    container_name: kafk-2
    hostname: kafk-2
    networks:
      - hdfs-net
      - kafka-net
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_NODE_ID=2
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafk-1:9093,2@kafk-2:9093,3@kafk-3:9093
      - KAFKA_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,PLAINTEXT://:9094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafk-2:9092,CONTROLLER://kafk-2:9093,PLAINTEXT://kafk-2:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_LOG_DIRS=/tmp/kraft-combined_logs
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    ports:
      - 39092:9094

  kafk-3:
    image: apache/kafka:3.9.0
    container_name: kafk-3
    hostname: kafk-3
    networks:
      - hdfs-net
      - kafka-net
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_NODE_ID=3
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafk-1:9093,2@kafk-2:9093,3@kafk-3:9093
      - KAFKA_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,PLAINTEXT://:9094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafk-3:9092,CONTROLLER://kafk-3:9093,PLAINTEXT://kafk-3:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_LOG_DIRS=/tmp/kraft-combined_logs
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
    ports:
      - 49092:9094

  connect:
    image: confluentinc/cp-kafka-connect:7.0.1
    container_name: connect
    depends_on:
      - kafk-1
      - kafk-2
      - kafk-3
    networks:
      - kafka-net
    environment:
      - CONNECT_BOOTSTRAP_SERVERS=kafk-1:9094,kafk-2:9094,kafk-3:9094
      - CONNECT_REST_ADVERTISED_HOST_NAME=connect
      - CONNECT_REST_LISTENERS=http://0.0.0.0:8083
      - CONNECT_GROUP_ID=connect-group
      - CONNECT_CONFIG_STORAGE_TOPIC=connect-config
      - CONNECT_OFFSET_STORAGE_TOPIC=connect-offsets
      - CONNECT_STATUS_STORAGE_TOPIC=connect-status
      - CONNECT_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - CONNECT_LOG4J_ROOT_LOGLEVEL=INFO
      - CONNECT_PLUGIN_PATH=/usr/share/java,/usr/share/confluent-hub-components
    ports:
      - 8083:8083
    command: [ "bash", "-c", "confluent-hub install --no-prompt confluentinc/kafka-connect-mqtt:latest && confluent-hub install --no-prompt confluentinc/kafka-connect-hdfs:latest && /etc/confluent/docker/run" ]

  spark:
    image: bitnami/spark:latest
    container_name: spark
    hostname: spark
    networks:
      - hdfs-net
      - kafka-net
    volumes:
      - ./spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
    depends_on:
      - hdfs-namenode
      - kafk-1
      - kafk-2
      - kafk-3
  hdfs-namenode:
    image: bde2020/hadoop-namenode:latest
    container_name: hdfs-namenode
    hostname: hdfs-namenode
    networks:
      - hdfs-net
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:8020
      - HDFS_CONF_dfs_replication=1
    ports:
      - "9870:9870"
      - "8020:8020"

  hdfs-datanode:
    image: bde2020/hadoop-datanode:latest
    container_name: hdfs-datanode
    hostname: hdfs-datanode
    networks:
      - hdfs-net
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:8020
      - HDFS_CONF_dfs_replication=1
    depends_on:
      - hdfs-namenode
